### ISSUE TITLE
self.header refers to the method and not the property

### ISSUE THREAD

**Issue by Harding-Stardust** [idapython/src#46]
https://github.com/idapython/src/blob/df6fcffcace653757f05d3ac588407d53c0d158d/python/idautils.py#L747

Gives the error:
File <redacted>\IDA\python\3\idautils.py:747, in peutils_t.__str__(self)
    746 def __str__(self):
--> 747     return "peutils_t(imagebase=%s, header=%s)" % (hex(self.imagebase), hex(self.header))

TypeError: 'method' object cannot be interpreted as an integer

There is a properry with the same name, I suggest renaming either the property or of the method.

**Comment by 0xeb** [comment]
Thank you, good catch. 

https://github.com/idapython/src/pull/47

We will merge soon.

**Comment by 0xeb** [comment]
Good catch. Fixed with #47.

Thanks!

**Comment by 0xeb** [comment]
fixed, thank you.
