### ISSUE TITLE
Python3 str does not have .decode(), this will cause the idaapi.has_mbcs to always be False

### ISSUE THREAD

**Issue by Harding-Stardust** [idapython/src#49]
https://github.com/idapython/src/blob/d34bb4b45a4b862d9af992e30220e9c344834ce3/pywraps/py_idaapi.py#LL407C10-L407C10

There are some .decode() that will fail on Python 3.

**Comment by williballenthin** [comment]
might be fixed by using a bytes literal, like: `b"".decode("UTF-8").encode("mbcs")` (note leading "b").

**Comment by Harding-Stardust** [comment]
Unfortunately not. The first decode "".decode("UTF-8") will return a str and that will in turn fail on the .encode("mbcs")

**Comment by williballenthin** [comment]
in Python3 the string object has a method `.encode(...)` that returns the string as bytes using the specified encoding. So, I think this would work:
<img width="390" alt="image" src="https://github.com/idapython/src/assets/156560/803c1445-7170-48d0-b289-371c20e4c0eb">

**Comment by Harding-Stardust** [comment]
You are correct, I read it as 2 decodes in a row. My bad!

**Comment by aundro** [comment]
Good catch, thank you! (will handle this soon)

**Comment by 0xeb** [comment]
@aundro , this should have been fixed by now? want to close the issue?

**Comment by aundro** [comment]
Indeed. Thank you for the heads-up.
