### ISSUE TITLE
ida_idp.set_processor_type causes internal error 1391

### ISSUE THREAD

**Issue by alexander-pick** [idapython/src#59]
Calling `ida_idp.set_processor_type("metapc", SETPROC_LOADER)` after startup with no IDB open, it won't set the default type but cause an internal error 1391. 

The error occurs on IDA Pro 8.3.

**Comment by 0xeb** [comment]
@alexander-pick , thanks for the report. that API call directly calls the SDK, therefore it will have the same behavior in C++.
So, this is best reported directly to support@hex-rays.com as it could be a bug in IDA kernel.

**Comment by alexander-pick** [comment]
Oh I had hope it's just some smaller issue. I will fill a report with the support.

**Comment by alexander-pick** [comment]
From the support response it seems that this call requires an open IDB, so it's not useable for setting the proc before creating an empty one (or switching the proc of the gdb debug backend as I tried to use it).

**Comment by skochinsky** [comment]
not a bug
