### ISSUE TITLE
Python 3.12 has removed "imp"

### ISSUE THREAD

**Issue by Harding-Stardust** [idapython/src#62]
https://github.com/idapython/src/blob/6142005952c489e684ad3aa8870b55b73baac90a/tools/dumpdoc.py#L17
fails since
>The imp module has been removed. (Contributed by Barry Warsaw in gh-98040.)

Source: https://docs.python.org/3.12/whatsnew/3.12.html

The same also for
https://github.com/idapython/src/blob/6142005952c489e684ad3aa8870b55b73baac90a/tools/inspect.py#L635

**Comment by githubsearcher11** [comment]
ida_idaapi.py needs to be fixed too.

**Comment by skochinsky** [comment]
Yes, full Python 3.12 support is coming in IDA 8.4

**Comment by skochinsky** [comment]
fixed with 8.4 release
