### ISSUE TITLE
Linux build error: process 'make' returned non-zero exit status 2

### ISSUE THREAD

**Issue by Drygord** [idapython/src#64]
In the final step of the build process, I got this error (formerly line 58 of build.py- where subprocess.check_call is called)

make: *** [../../allmake.mak:806: obj/x64_linux_gcc_32_opt/idapython.o] Error 1
Traceback (most recent call last):
  File "/home/dry/IDA/idasdk75/plugins/idapython/build.py", line 60, in run
    subprocess.check_call(proc_argv, env=full_env)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.

Any idea what error 2 stands for and how to resolve this? I followed all steps pretty much exactly.

**Comment by skochinsky** [comment]
it should be `PYTHON_VERSION_MAJOR` and  `PYTHON_VERSION_MINOR`, not `PYTHON_MAJOR_VERSION`. See `defaults.mk` in the root of the SDK.
