### ISSUE TITLE
get_tev_reg_mem not in idaapi.py

### ISSUE THREAD

**Issue by gitttt** [idapython/src#7]
Calling `idc.GetTevRegMem()` leads to this error:

> File "/opt/ida-6.9/python/idc.py", line 8332, in GetTevRegMem
>     return idaapi.get_tev_reg_mem(tev, idx)
> AttributeError: 'module' object has no attribute 'get_tev_reg_mem'

I took a look in to the `idaapi.py` and indeed, the corresponding function is not there.
Is this a hexrays issue?

**Comment by aundro** [comment]
Please address bug reports & feature requests to <support@hex-rays.com>, including your license ID.

Thanks!

**Comment by gitttt** [comment]
Done
